version: 2

sphinx:
  fail_on_warning: true

python:
  version: 3.8
  install:
    # Equivalent to 'pip install .'
    - method: pip
      path: .
    # Equivalent to 'pip install .[docs]'
    - method: pip
      path: .
      extra_requirements:
        - docs
